"""create urls table

Revision ID: 0132ba841ec5
Revises: 
Create Date: 2026-03-02 09:13:50.764599

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '0132ba841ec5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
